<meta charset="utf-8" />
<div class="form_div">
<form id="form" action="" method="POST">
    <label>Тема: <br/><input maxlength="100" minlength="5" type="text" id="name" placeholder="Тема звернення" name="topic" required></label>
 	<label>Для чого? <span class='why'><br/> Будь ласка, коротко опишіть чому, на Вашу думку, проблема або пропозиція є важливою. (до 150 символів)</span> <br/><textarea name="benefit" maxlength="150" minlength="50" required></textarea></label>
    <label>Текст звернення: <br/><textarea minlength="50" name="text" required></textarea></label>
    <input type="submit" value="OK">
</form>
</div>